about/urls.py
from django.urls import path
from .views import AboutListView

app_name = "about"


urlpatterns = [
    path("about/", AboutListView.as_view(), name="about"),
]

pages/urls.py
from django.urls import path
from .views import HomePage

app_name = "pages"


urlpatterns = [
    path("", HomePage.as_view(), name="home"),

]

services/urls.py
from django.urls import path
from .views import ServiceListView

app_name = "services"

urlpatterns = [
    path("service/", ServiceListView.as_view(), name="serve"),
]

web_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("serve/", include("services.urls")),
        path("about/", include("about.urls")),
        path("", include("pages.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

about/models.py
from django.db import models


class AboutPage(models.Model):
    title = models.CharField(max_length=150)
    introdcution = models.TextField()
    location = models.TextField()
    services = models.TextField()

    def __str__(self):
        return self.title[:25]

    def __str__(self):
        return self.introdcution[:25]

    def __str__(self):
        return self.location[:25]

    def __str__(self):
        return self.services[:25]

pages/models.py
from django.db import models


class HomePost(models.Model):
    artist = models.CharField(max_length=50, blank=True)
    art = models.FileField(upload_to="uploads")
    info = models.CharField(max_length=150, blank=True)

services/models.py
from django.db import models


class ServicesModel(models.Model):
    service_page_title = models.CharField(max_length=150)
    name_of_service = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    comments = models.TextField()

    def __str__(self):
        return f"Services Page Title: {self.service_page_title} - The name of the service:  {self.name_of_service} - Price: {self.price}UGX - Notes about service: {self.comments} "

about/views.py
from django.views.generic import ListView
from .models import AboutPage


class AboutListView(ListView):
    model = AboutPage
    template_name = "about.html"
    context_object_name = "about_post"

pages/views.py
from django.views.generic import ListView
from .models import HomePost


class HomePage(ListView):
    model = HomePost
    template_name = "home.html"
    context_object_name = "home_post"

services/views.py
from django.views.generic import ListView
from .models import ServicesModel


class ServiceListView(ListView):
    model = ServicesModel
    template_name = "serve.html"
    context_object_name = "services_post"

about/templates/about.html
{% extends "_base.html" %} {% block content %}
<div class="container_about">
  <li>{{ post.title }}</li>

  <div class="list_container">
    {% for post in about_post_list %}
    <ul class='about_group'>
      <li class='about_item'>{{ post.introdcution }}</li>
      <li class='about_item'> {{ post.location }}</li>
      <li class='about_item' >{{ post.services }}</li>
    </ul>
    {% endfor %}
  </div>
</div>
{% endblock content %}

pages/templates/home.html
{% extends '_base.html' %} {% block content %}

<div class="container">
  <h1 class="header1">Tyreka Nails & Makeup</h1>

  <div class="container2">
    {% for post in home_post_list %}
    <div class="item">
      <img class="item" src="{{ post.art.url }}" alt="{{ post.artist }}" />
      <div class="postInfo">{{ post.info }}</div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

services/templates/serve.html
{% extends "_base.html" %} {% block content %}
<div class="serviceContainer">
  {% for post in services_post_list %}
  <div class="servicesList">
    <title>{{ post.service_page_title }}</title>
    <ul>
      <li>{{ post.name_of_service }}</li>
      <li>{{ post.price }}</li>
    </ul>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>TyNails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/pages.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}" />
  </head>
  <body>
    <nav class="navbar">
      <ul class="listGroup">
        <li class="logo">
          <a class="linkLogo" href="{% url 'pages:home' %}">TyNails</a>
        </li>
        <li class="listItem">
          <a class="linkItem" href="{% url 'pages:home' %}">Home</a>
        </li>
        <li class="listItem">
          <a class="linkItem" href="{% url 'about:about' %}">About</a>
        </li>
        <li class="listItem">
          <a class="linkItem" href="{% url 'services:serve' %}">Services</a>
        </li>
      </ul>
    </nav>
    {% block content %}{% endblock content %}
  </body>
</html>